name: Android Build (APK + AAB)
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_android:
    name: Build Android AAB & APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install deps
        run: flutter pub get
      - name: Prepare keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/debug/afd-debug.jks; fi
      - name: Build AAB
        run: flutter build appbundle --release
      - name: Build APK
        run: flutter build apk --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-release-artifacts
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
